---
title: "Cleaning and Wrangling"
format: html
editor: visual
---

```{r}
#| message: false
# load packages
library(dplyr)
library(tidyr)
library(readr)
```

```{r}
## Read in our data
catch_original <- readr::read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

```{r}
colnames(catch_original)
head(catch_original)
summary(catch_original)
unique(catch_original$Region)
```

```{r}
catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

catch_data <- catch_original %>% 
  select(-All, -notesRegCode)

head(catch_data)
```

```{r}
glimpse(catch_data)
```

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = as.numeric(Chinook))
```

```{r}
# find NA values in catch_clean table
is.na(catch_clean$Chinook)

i <- which(is.na(catch_clean$Chinook))

catch_data[i, ]

catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(condition = Chinook == "I",
                           true = "1",
                           false = Chinook),
         Chinook = as.numeric(Chinook)
         )

catch_clean[i, ]
head(catch_clean)
```

```{r}
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year),
               names_to = "Species",
               values_to = "Catch"
               )

catch_wide <- catch_long %>% 
  pivot_wider(names_from = Species,
              values_from = Catch)
```

```{r}
catch_long <- catch_long %>% 
  rename(catch_thousands = Catch)
head(catch_long)
```

```{r}
catch_long <- catch_long %>% 
  mutate(Catch = catch_thousands * 1000)

head(catch_long)
```

```{r}
jk = 1000
jk = jk + 5
jk = jk + 10
jk
```

```{r}
jk <- 1000
jk <- jk %>% 
  sum(5) %>% 
  sum(10)

jk
```

```{r}

```

